services:
  - name: ai-gen-api
    envVars:
      - key: PORT
        value: 5000
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && pip install huggingface_hub[hf_xet] && pip install accelerate"
    startCommand: "python app.py"
    type: web
